# Generated by Django 5.0.3 on 2024-03-18 01:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleEntity",
            fields=[
                (
                    "article_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=1000)),
                ("upvotes", models.IntegerField()),
                ("downvotes", models.IntegerField()),
            ],
            options={
                "db_table": "articulos",
            },
        ),
    ]
