# Generated by Django 5.0.3 on 2024-03-15 23:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VotingUserEntity",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("karma", models.IntegerField()),
            ],
            options={
                "db_table": "voting_user",
            },
        ),
        migrations.CreateModel(
            name="ArticleVoteEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("article_id", models.UUIDField()),
                (
                    "vote",
                    models.CharField(
                        choices=[("up", "UP"), ("down", "DOWN")], max_length=4
                    ),
                ),
            ],
            options={
                "db_table": "article_vote",
                "unique_together": {("user_id", "article_id")},
            },
        ),
    ]
